import { 
  Lightbulb, 
  GraduationCap, 
  CalendarCheck, 
  Building2, 
  FileText, 
  Scroll, 
  GitBranch, 
  BarChart3, 
  Calendar, 
  AlertTriangle,
  MapPin,
  Check,
  Lock,
  Play,
  BookOpen,
  Search,
  FileBadge,
  Rocket,
  Code,
  Warehouse,
  Shield,
  Zap,
  Target,
  UserCheck,
  Gauge,
  Brain,
  TableProperties,
  RotateCcw,
  Clock,
  Bot,
  Smile,
  AlertCircle,
  Star,
  ArrowLeft,
  Flame,
  X,
  ShieldCheck,
  CheckCircle,
  XCircle,
  Gavel,
  Tags,
  FileSearch,
  Briefcase,
  History,
  ClipboardCheck,
  Award,
  Shuffle,
  FileCheck,
  ListChecks
} from 'lucide-react';

export const iconMap = {
  // Common
  'Lightbulb': Lightbulb,
  'GraduationCap': GraduationCap,
  'CalendarCheck': CalendarCheck,
  'Building2': Building2,
  'FileText': FileText,
  'Scroll': Scroll,
  'GitBranch': GitBranch,
  'BarChart3': BarChart3,
  'Calendar': Calendar,
  'AlertTriangle': AlertTriangle,
  'MapPin': MapPin,
  'Check': Check,
  'Lock': Lock,
  'Play': Play,
  'BookOpen': BookOpen,
  'Search': Search,
  'FileBadge': FileBadge,
  'Rocket': Rocket,
  'Code': Code,
  'Warehouse': Warehouse,
  'FileShield': Shield,
  'Zap': Zap,
  'Target': Target,
  'UserCheck': UserCheck,
  'Gauge': Gauge,
  'Brain': Brain,
  'TableProperties': TableProperties,
  'RotateCcw': RotateCcw,
  'Clock': Clock,
  'Bot': Bot,
  'Smile': Smile,
  'AlertCircle': AlertCircle,
  'Star': Star,
  'ArrowLeft': ArrowLeft,
  'Flame': Flame,
  'X': X,
  'ShieldCheck': ShieldCheck,
  'CheckCircle': CheckCircle,
  'XCircle': XCircle,
  'Gavel': Gavel,
  'Tags': Tags,
  'FileSearch': FileSearch,
  'Briefcase': Briefcase,
  'History': History,
  'ClipboardCheck': ClipboardCheck,

  'Award': Award,
  'Shuffle': Shuffle,
  'FileCheck': FileCheck,
  'ListChecks': ListChecks,

  // Legacy mappings (FontAwesome strings found in data)
  'fa-lightbulb': Lightbulb,
  'fa-user-graduate': GraduationCap,
  'fa-calendar-check': CalendarCheck,
  'fa-university': Building2,
  'fa-file-invoice': FileText,
  'fa-scroll': Scroll,
  'fa-code-branch': GitBranch,
  'fa-chart-bar': BarChart3,
  'fa-calendar': Calendar,
  'fa-triangle-exclamation': AlertTriangle,
  'fa-map-location-dot': MapPin,
  'fa-check': Check,
  'fa-lock': Lock,
  'fa-play': Play,
  'fa-book-open': BookOpen,
  'fa-magnifying-glass': Search,
  'fa-certificate': FileBadge,
  'fa-rocket': Rocket,
  'fa-code': Code,
  'fa-warehouse': Warehouse,
  'fa-file-shield': Shield,
  'fa-bolt': Zap,
  'fa-bullseye': Target,
  'fa-user-check': UserCheck,
  'fa-gauge-high': Gauge,
  'fa-brain': Brain,
  'fa-table-list': TableProperties,
  'fa-rotate-right': RotateCcw,
  'fa-clock': Clock,
  'fa-robot': Bot,
  'fa-smile-beam': Smile,
  'fa-exclamation-circle': AlertCircle,
  'fa-star': Star,
  'fa-arrow-left': ArrowLeft,
  'fa-fire': Flame,
  'fa-xmark': X,
  'fa-shield-halved': ShieldCheck,
  'fa-award': Award,
  'fa-shuffle': Shuffle,
  'fa-gavel': Gavel,
  'fa-tags': Tags,
  'fa-circle-check': CheckCircle,
  'fa-circle-xmark': XCircle
};

export const getIcon = (name) => {
  if (!name) return Lightbulb;
  
  // If it's a FontAwesome string like "fa-solid fa-check", clean it
  const cleanName = name.replace('fa-solid ', '').replace('fa-brands ', '').replace('fa-regular ', '').trim();
  
  return iconMap[cleanName] || iconMap[name] || Lightbulb;
};
